"""add finding_decisions table

Revision ID: b262cc5c634d
Revises: da59ecb70777
Create Date: 2026-09-18 17:58:57.462245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b262cc5c634d'
down_revision: Union[str, Sequence[str], None] = 'da59ecb70777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=16), nullable=False),
    sa.Column('axis', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('signal', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('github_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo', 'pr_number', 'fingerprint', name='uq_decision')
    )
    op.create_index(op.f('ix_finding_decisions_fingerprint'), 'finding_decisions', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_finding_decisions_pr_number'), 'finding_decisions', ['pr_number'], unique=False)
    op.create_index(op.f('ix_finding_decisions_repo'), 'finding_decisions', ['repo'], unique=False)
    op.create_table('llm_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('findings_json', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_cache_cache_key'), 'llm_cache', ['cache_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_cache_cache_key'), table_name='llm_cache')
    op.drop_table('llm_cache')
    op.drop_index(op.f('ix_finding_decisions_repo'), table_name='finding_decisions')
    op.drop_index(op.f('ix_finding_decisions_pr_number'), table_name='finding_decisions')
    op.drop_index(op.f('ix_finding_decisions_fingerprint'), table_name='finding_decisions')
    op.drop_table('finding_decisions')
    # ### end Alembic commands ###
